name: "游늻 Estilo de C칩digo (style)"
description: "Relate uma issue sobre formata칞칚o e estilo do c칩digo."
title: "style: "
labels: ["style"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Descri칞칚o"
      description: "Descreva a mudan칞a de estilo de c칩digo necess치ria. Aponte os arquivos ou trechos que precisam de formata칞칚o/lint."
    validations:
      required: true
